export const useBriefingExport = () => {
  const exportMarkdown = (routeId: string, routeData: any, weights: any) => {
    const getGrade = (score: number) => {
      if (score >= 80) return 'A (Exceptional)';
      if (score >= 60) return 'B (Strong Alignment)';
      if (score >= 40) return 'C (Neutral)';
      if (score >= 20) return 'D (Sub-Optimal)';
      return 'E (Critical Gap)';
    };

    const content = `
# Route Equity Briefing: ${routeData.route_name}
**Date:** ${new Date().toLocaleDateString()}
**Route ID:** ${routeId}
**REI Score:** ${routeData.rei_score} / 100
**Letter Grade:** ${getGrade(routeData.rei_score)}

---

## ⚖️ Policy Calibration
The following weights were applied to this analysis:
*   **Social Vulnerability:** ${(weights.vulnerability * 100).toFixed(0)}%
*   **Off Peak Service:** ${(weights.temporal * 100).toFixed(0)}%
*   **Network Monopoly:** ${(weights.monopoly * 100).toFixed(0)}%
*   **Opportunity Access:** ${(weights.opportunity * 100).toFixed(0)}%

## 📊 Score Drivers (SHAP Analysis)
The route's performance is driven by the following factors:
*   **Vulnerability Impact:** +${(routeData.vuln_score * weights.vulnerability).toFixed(1)}
*   **Off Peak Service Impact:** +${(routeData.temp_score * weights.temporal).toFixed(1)}
*   **Monopoly Impact:** +${(routeData.mono_score * weights.monopoly).toFixed(1)}
*   **Opportunity Impact:** +${(routeData.opp_score * weights.opportunity).toFixed(1)}

## 📝 Strategic Recommendation
This corridor serves a population of **${(routeData.pop_served || 0).toLocaleString()}**. Based on the current weighting of ${(weights.vulnerability * 100).toFixed(0)}% Social Vulnerability, this route is classified as a **${getGrade(routeData.rei_score)}** priority for equity-based investment.

---
*Generated by Route Equity Scorecard OS v1.0*
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Route_${routeId}_Briefing.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return { exportMarkdown };
};
